DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS CLIENT;

CREATE TABLE CLIENT (
       ID SERIAL
     , FIRST_NAME VARCHAR(60) NOT NULL
     , LAST_NAME VARCHAR(40) NOT NULL
     , PRIMARY KEY (ID)
);


CREATE TABLE ADDRESS (
       ID SERIAL
     , CITY VARCHAR(60) NOT NULL
     , STREET VARCHAR(40) NOT NULL
     , HOUSE VARCHAR(40) NOT NULL
     , CLIENT_ID INT  NOT NULL
     , CONSTRAINT FK_ADDRESS_1 FOREIGN KEY (CLIENT_ID)
                       REFERENCES CLIENT (ID) ON DELETE CASCADE
     , PRIMARY KEY (ID)
);

